version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: builder
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: electron-builder
    versions:
    - 22.9.1
